name: Run Tests
on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Restore Steam config.vdf
        env:
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
        run: |
          mkdir -p ~/.steam/config
          echo "$STEAM_CONFIG_VDF" | base64 --decode > ~/.steam/config/config.vdf
          chmod 600 ~/.steam/config/config.vdf
          
          echo "DEBUG: ~/.steam/config/config.vdf exists:"
          ls -l ~/.steam/config

      - name: Test SteamCMD login
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        run: |
          echo "Logging in with cached credentials..."
          steamcmd +login "$STEAM_USERNAME" +quit

      - name: Install Spacewar (480)
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        run: |
          steamcmd \
            +login "$STEAM_USERNAME" \
            +app_update 480 validate \
            +quit

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
