name: Run Tests
on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar lib32gcc-s1

      - name: Download SteamCMD
        run: |
          mkdir -p ~/steamcmd
          cd ~/steamcmd
          wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
          tar -xvzf steamcmd_linux.tar.gz

      - name: Restore Steam config.vdf
        env:
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
        run: |
          mkdir -p ~/steamcmd/config
          echo "$STEAM_CONFIG_VDF" | base64 --decode > ~/steamcmd/config/config.vdf
          chmod 777 ~/steamcmd/config/config.vdf
          
          mkdir -p ~/Steam/config
          echo "$STEAM_CONFIG_VDF" | base64 --decode > ~/Steam/config/config.vdf
          chmod 777 ~/Steam/config/config.vdf

      - name: Test SteamCMD login
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        run: |
          echo "Logging in with cached credentials..."
          ~/steamcmd/steamcmd.sh +login "$STEAM_USERNAME" +quit

      - name: Install Spacewar (480)
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        run: |
          ~/steamcmd/steamcmd.sh \
            +login "$STEAM_USERNAME" \
            +app_update 480 validate \
            +quit

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
